spring:
  application:
    name: wooriLearn

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: ${JWT_SECRET}
    access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:31536000000}

  env:
    app-key: ${spring.env.app-key}
    secret-key: ${spring.env.secret-key}
  
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    

   data:
    redis:
      ttl: 10m

client:
  base-url: ${CLIENT_BASE_URL}

account:
  external-auth:
    base-url: ${ACCOUNT_EXTERNAL_AUTH_BASE_URL}
    request-path: ${ACCOUNT_EXTERNAL_AUTH_REQUEST_PATH:/otp}

external:
  bank:
    base-url: ${external.bank.base-url}
    account-url: ${external.bank.account-url}

api:
  client:
    connect-timeout: 5s
    read-timeout: 5s
