spring:
  application:
    name: wooriLearn

  profiles:
    active: dev

  # mysql 데이터
  datasource:
    url: jdbc:mysql://localhost:3306/wooriLearn?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # url: jdbc:mysql://192.168.0.79:8506/wooriLearn?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: 1nGmLQMnCQri6kT7jCy0rSzzcAJNR8BoZzDYr/tcVTnwZ/173LuUX3gAwZlI6NRExH0CffzkizyE75VX1Mqw7w==
    access-expiration: 3600000
    refresh-expiration: 31536000000

  data:
    redis:
      host: localhost
      port: 6379
      ttl: 10m

  cache:
    type: redis
    redis:
      time-to-live: 300000

  env:
    app-key: "YOUR_APP_KEY_123"
    secret-key: "MY_SECRET_ABC123"
    client-id: "woori-learn"

app:
  rate-limit:
    enabled: true
    capacity: 60
    refill-tokens: 60
    refill-duration-minutes: 1

  auto-payment:
    max-amount: 5000000
    amount-limit-enabled: true

client:
  base-url: http://localhost:3001 # 프론트 서버 주소

account:
  external-auth:
    base-url: http://localhost:8081
    request-path: /otp
    connect-timeout-ms: 1500
    read-timeout-ms: 3000

external:
  bank:
    base-url: http://localhost:8081 # 은행 서버 주소
    account-url: /account

api:
  client:
    connect-timeout: 5s
    read-timeout: 5s